### ISSUE TITLE
Can you change SleekXMPP (dead project) to Slixmpp (Successor)

### ISSUE THREAD

**Issue by Neustradamus** [egoexpress/innoxmpp#13]
Can you update the code for compatibility with the successor of SleekXMPP?
- https://lab.louiz.org/poezio/slixmpp
- https://github.com/poezio/slixmpp

**Comment by egoexpress** [comment]
As this project is as dead as SleekXMPP itself I guess there is not much to get out of an update to SliXMPP.

OTOH: If it is a drop-in replacement for SleekXMPP with a compatible API, a replacement of sleekxmpp with slixmpp in [GenericBot.py]( https://github.com/egoexpress/innoxmpp/blob/master/bots/GenericBot.py) would be enough, I guess.
